### PR TITLE
Fix lu converter to handle required feature at top level and whitespaces at child entity name correctly

### LINKED ISSUE #1137: [bf-lu] Non-child entities required features are converted to roles when converting lu to JSON
## Versions
What CLI version are you using.
bf-lu 4.11.1

What Nodejs version are you using
v10.18.1

What command-line interpreters are you using
Powershell

What OS are you using
Windows

## Describe the bug
When a required feature is used in a LUIS Lu file on a non-child entity, it gets translated as a role instead of a required feature.

## To Reproduce
Convert a JSON app to Lu that has the following entities
```json
"entities": [
  {
    "name": "some entity"
  },
  {
    "name": "another entity",
    "features": [
      {
        "modelName": "some entity",
        "isRequired": true
      }
    ]
  }
]
```
It gets converted to this, which makes sense.
```
> # Entity definitions

@ ml "some_entity"

@ some_entity "another entity"
```
But when it's converted back to JSON, it becomes
```json
"entities": [
  {
    "name": "some_entity",
    "roles": [
      "another entity"
    ]
  }
]
```
## Expected behavior
Converting to Lu then back to JSON should return the original JSON file.

[bug]

### PR DESCRIPTION
**Pull request by feich-ms**
Fix #1137 and #1138. The main fixes are listed as below:

- Fix the top level **required("isRequired": true)** feature not converted correctly issue
Before the fix, for the luis json below
```
"entities": [
  {
    "name": "another_entity",
    "features": [
      {
        "modelName": "some_entity",
        "isRequired": true
      }
    ]
  },
  {
    "name": "some_entity"
  }
]
```

It will be converted to below lu format, but the first line below will be recognized as `@ <entity_name> <role>` when converting back to json, so this will cause inconsistency between lu and json converting.
```
@ some_entity another_entity
@ ml some_entity
```

After the fix, the above json will be converted to below. Here `*` appended to feature name is used to identify if it's required or not. When converting this lu format to json, it will use `*` to decide filling the isRequired with true.
```
@ ml another_entity useFeature some_entity*
@ ml some_entity
```

- Fix the whitespace issue in child entity name. This is easy to fix, just apply the `writeEntityName` function that was handling entity name whitespace to ensure quotation marks are added correctly.

New test cases are added to verify the fixes. All existing tests remain unchanged.

### CODE REVIEW

**Comment by feich-ms** [comment]
@munozemilio could you please help to review and verify? Thanks.

**Comment by feich-ms** [comment]
@munozemilio I added validations for entity, intent and phraselist names that could be used as features. They cannot contain special char * in their name definitions(align with luis portal). With this validations, we can make sure feature names with * at the tail can be used to represent the required feature. Some entity name validations are moved to parseFileContents file from lu parser to decouple the luis specific limitations per your suggestions. Pls help to take a look. Thanks.

File: packages/lu/src/parser/lufile/visitor.js [hunk 1]
```diff
@@ -46,12 +46,6 @@ class Visitor {
     static recurselyResolveTokenizedUtterance(tokUtt, entities, errorMsgs, srcUtterance) {
         for (const item of tokUtt) {
             if (item === Object(item)) {
-                let entityName = item.entityName.trim()
```
Comment (munozemilio) [inline packages/lu/src/parser/lufile/visitor.js:49]: This may reduce flexibility for other NLU providers if they want to consume LU format in case they allow those characters in their entity names. On the other hand LU format is already very LUIS oriented.

**Review by munozemilio — APPROVED** [review]
