### PR TITLE
Luis command handle empty lu file

### LINKED ISSUE #230: Empty .lu file creates error on luis:convert
Problem:

When using an empty .lu file, luis:convert errors out.

```
Unknown error during execution. Please file an issue on https://github.com/microsoft/botframework-cli/issues
Cannot destructure property `fileContent` of 'undefined' or 'null'.
```

Repro steps:

1. Create an empty Main.lu file
2. run `bf luis:convert--in ./Main.lu`
3. Get error

Desired behavior:

It should handle empty files.

### PR DESCRIPTION
**Pull request by munozemilio**
Fixes #230, #241, #247, #239, #246

### CODE REVIEW

File: packages/lu/src/parser/converters/lumerger.js [hunk 1]
```diff
@@ -327,7 +327,11 @@ const readLuFile = function(file) {
 }
 
 const parseLuFile = async function(file, log, luis_culture) {
-    let parsedContent = '';
+    let parsedContent = ''
+    if (!file) {
+        let error = BuildDiagnostic({ message: `Sorry, empty file content` })
```
Comment (christopheranderson) [inline packages/lu/src/parser/converters/lumerger.js]: [blocking] All error messages should provide guidance to users on how to resolve them.

@vishwacsena - is erroring on empty `.lu` the correct behavior here? If so, what action should the user take.

Alternatively, I feel like a warning with no-op might be a better pattern, especially when passed in a directory reference.

Comment (christopheranderson) [reply packages/lu/src/parser/converters/lumerger.js]: Talked offline. We're going to go with error. Suggested error text:

> Cannot parse empty ${filename}. Please add content to the file or remove it.

File: packages/qnamaker/src/commands/qnamaker/kb/export.ts [hunk 2]
```diff
@@ -4,7 +4,7 @@ const exportKbJSON = require('./../../../../utils/payloads/exportkb')
 import {Inputs, processInputs} from '../../../utils/qnamakerbase'
 
 export default class QnamakerKbExport extends Command {
-  static description = 'Export a knowledgebase to .json file'
+  static description = 'Echos a knowledgebase .json to stdout'
```
Comment (christopheranderson) [inline packages/qnamaker/src/commands/qnamaker/kb/export.ts]:
```suggestion
  static description = 'Echos a knowledgebase json to stdout'
```

[nit] `.json` is a file extenion. `json` is a data format.
