### PR TITLE
syncLabelResolverEx should return after addBatch

### LINKED ISSUE #1262: Don't do incremental update to LabelResolver when there is no existing blu file
Doing incremental update is way slower when LabelResolver.addBatch when there is no existing blu file.  This is a regression from 4.13 version for when there is no existing snapshot.

### PR DESCRIPTION
**Pull request by tsuwandy**
Fix #1262

### CODE REVIEW

File: packages/orchestratorlib/src/build.ts [hunk 1]
```diff
@@ -161,6 +161,7 @@ export class OrchestratorBuild {
       Utility.debuggingLog('OrchestratorBuild.syncLabelResolverEx(), ready to call LabelResolver.addBatch()');
       LabelResolver.addBatch(target);
       Utility.debuggingLog('OrchestratorBuild.syncLabelResolverEx(), after calling LabelResolver.addBatch()');
+      return;
```
Comment (munozemilio) [inline packages/orchestratorlib/src/build.ts:164]: Should we add a test to catch this scenario?

**Review by daveta — APPROVED** [review]

**Review by hcyang — APPROVED** [review]

**Review by munozemilio — CHANGES_REQUESTED** [review]
If this was not caught by the tests, maybe we should add one

**Review by munozemilio — APPROVED** [review]
