### PR TITLE
Adding fix for translation commands

### LINKED ISSUE #1135: luis:translate Text translator service 401 error
## Versions
I am using `@microsoft/botframework-cli/4.11.1 linux-x64 node-v12.16.1`

## Describe the bug
When trying to call `bf luis:translate` using my Text Translator service provisioned in my Azure subscription, it gives an error saying **"Text translator service call failed with [401] : Unauthorized."**

After investigating a bit, it seems that in file https://github.com/microsoft/botframework-cli/blob/62f691eaec547186dd9ab6ea9f59c89a8bbd7b27/packages/lu/src/parser/lufile/translate-helpers.js#L263 we are missing a header property "Ocp-Apim-Subscription-Region" according to the Translator documentation: https://docs.microsoft.com/en-us/azure/cognitive-services/translator/quickstart-translator?tabs=nodejs. 

## To Reproduce
1. Create a Translator service in your Azure subscription
2. Collect the Translator key
3. Invoke  `bf luis:translate --in test.lu --out test-pt.lu --force --tgtlang "pt-PT" --translate_comments --translatekey ${YOUR_TRANSLATOR_KEY}`
4. See error like:
Text translator service call failed with [401] : Unauthorized.
Please check key & language code validity

## Expected behavior
It should create a new file with the result of the translation.

## Additional context

[bug]

### PR DESCRIPTION
**Pull request by munozemilio**
fixes #1135

### CODE REVIEW

File: packages/lu/src/parser/lufile/translate-helpers.js [hunk 1]
```diff
@@ -27,8 +37,10 @@ const translateHelpers = {
      * @returns {string} Localized file content
      * @throws {exception} Throws on errors. exception object includes errCode and text. 
      */
-    parseAndTranslate : async function(fileContent, subscriptionKey, to_lang, src_lang, translate_comments, translate_link_text, log, batch_translate) {
-        let batch_translate_size = batch_translate ? parseInt(batch_translate) : MAX_TRANSLATE_BATCH_SIZE;
+    parseAndTranslate : async function(fileContent, ts) {
```
Comment (feich-ms) [inline packages/lu/src/parser/lufile/translate-helpers.js:40]: param headers should be aligned with new parameters definitions of ts

File: packages/lu/src/parser/lufile/translate-helpers.js [hunk 2]
```diff
@@ -251,19 +263,24 @@ const translateHelpers = {
      * @returns {object} response from MT call.
      * @throws {exception} Throws on errors. exception object includes errCode and text. 
      */
-    translateText: async function(text, subscriptionKey, to_lang, from_lang) {
+    translateText: async function(text, translationSettings) {
```
Comment (feich-ms) [inline packages/lu/src/parser/lufile/translate-helpers.js:266]: param headers should be aligned with new parameters definitions of translationSettings

**Review by feich-ms — APPROVED** [review]
Some function param header descriptions are outdated
