### PR TITLE
Fix import and entity issues

### LINKED ISSUE #1270: bf-orchestrator should not swallow errors
## Versions
@microsoft/bf-orchestrator-cli 4.14.1

## Describe the bug
Orchestrator should not swallow underlying errors.  For example in OrchestratorHelp.ts you see this code:
```
    } catch (error) {
      throw new Error(`Failed to parse ${filePath}`);
    }
```
This means you have no idea why parsing failed because error is not reflected.

## To Reproduce
1. Create an LU file with improper syntax
2. bf orchestrator:create with that file

## Expected behavior
You should see underlying parsing errors.

[bug]

### PR DESCRIPTION
**Pull request by chrimc62**
Fixes #1270 #1271 #1272 #1273

This fixes a number of issues with multi-level imports and with entity detection.

### CODE REVIEW

**Review by hcyang — APPROVED** [review]

File: packages/orchestratorlib/src/orchestratorhelper.ts [hunk 1]
```diff
@@ -70,10 +71,14 @@ export class OrchestratorHelper {
     return resolvedFilePath;
   }
 
-  public static deleteFile(filePath: string)  {
+  public static deleteFile(filePath: string) {
     fs.unlinkSync(filePath);
   }
 
+  public static label(name: string, offset: number, length: number): any {
```
Comment (joshgummersall) [inline packages/orchestratorlib/src/orchestratorhelper.ts:78]: Would be good to use a better return type than `any`.

File: packages/orchestratorlib/src/orchestratorhelper.ts [hunk 2]
```diff
@@ -1137,15 +1144,13 @@ export class OrchestratorHelper {
   static findLuFiles(srcId: string, idsToFind: string[]): any[] {
     const baseDir: string = path.dirname(srcId);
     const retPayload: any[] = [];
-    (idsToFind || []).forEach((ask: any)  => {
+    (idsToFind || []).forEach((ask: any) => {
```
Comment (joshgummersall) [inline packages/orchestratorlib/src/orchestratorhelper.ts:1147]: Since you're touching this line, you should be able to omit the types on this function as they're inferred from the `idsToFind` argument. Small nit, but seeing `any` is almost always a code smell.

```typescript
idsToFind?.forEach((ask) => {
  ...
});
```

**Review by joshgummersall — APPROVED** [review]
Couple comments, I'll approve though as they are minor changes.

File: packages/orchestratorlib/src/orchestratorhelper.ts (hunk 2 above)
Comment (chrimc62) [reply packages/orchestratorlib/src/orchestratorhelper.ts:1147]: Removing the any causes VS code to complain.

Comment (joshgummersall) [reply packages/orchestratorlib/src/orchestratorhelper.ts:1147]: It should! In line `1144` the type of `idsToFind` is `string[]` whereas below it's treated as an object. What's going on there?

Comment (chrimc62) [reply packages/orchestratorlib/src/orchestratorhelper.ts]: Sigh.  This code is being used in a non-typescript context and was written by a non-typescript developer.  I'll fix it.

File: .vscode/launch.json [hunk 3]
```diff
@@ -44,6 +49,33 @@
...
+      "preLaunchTask": "${defaultBuildTask}",
+      "program": "${workspaceFolder}/packages/orchestrator/bin/run",
+      "outputCapture": "std",
+      "outFiles": [
+        "${workspaceFolder}/packages/orchestrator/lib/**"
+      ],
+      "args": [
+        "orchestrator:create",
+        "--in",
+        "C:/Users/chrim/AppData/Local/Temp/sandwich.out/language-understanding/en-us/sandwich.en-us.lu",
```
Comment (munozemilio) [inline .vscode/launch.json:65]: Seems this test is a bit hardcoded

**Review by munozemilio — APPROVED** [review]
